### ISSUE TITLE
Article excerpt does not display on page single

### ISSUE THREAD

**Issue by michaelkpate** [brahm/clean-blog-textpattern#6]
page single line 20:

`<h2 class="subheading"><txp:excerpt /></h2>`

Unfortunately, this generates an error:

> Textpattern Notice: Article tags cannot be used outside an article context.

To correct it, I made a new form called clean_excerpt:

`<txp:excerpt />`

and replaced the code on line 20 with:

`<h2 class="subheading"><txp:article form="clean_excerpt" limit="1" /></h2>`

**Comment by brahm** [comment]
Man, thank you for all pointed bugs. I have corrected all and include you in the credits.
